import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en'; // 'en' or 'hi'

  String get currentLanguage => _currentLanguage;
  bool get isHindi => _currentLanguage == 'hi';

  void toggleLanguage() {
    _currentLanguage = _currentLanguage == 'en' ? 'hi' : 'en';
    notifyListeners();
  }

  String getText(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  // Translations
  final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Picory',
      'tagline': 'Shaadi Se Delivery Tak — Har Kaam Ek App Mein.',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'enter_name': 'Please enter your name',
      'enter_email': 'Please enter your email',
      'enter_phone': 'Please enter your phone number',
      'enter_password': 'Please enter your password',
      'password_length': 'Password must be at least 6 characters',
      'password_not_match': 'Passwords do not match',
      'phone': 'Phone',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'home': 'Home',
      'events': 'Events',
      'profile': 'Profile',
      'active_plan': 'Active Plan',
      'upgrade_plan': 'Upgrade Plan',
      'create_event': 'Create Event',
      'event_name': 'Event Name',
      'event_date': 'Event Date',
      'deal_amount': 'Deal Amount',
      'amount_received': 'Amount Received',
      'total_photos': 'Total Photos',
      'add_photos': 'Add Photos',
      'add_files': 'Add Files',
      'permissions': 'Permissions',
      'allow_download': 'Allow Download',
      'allow_share': 'Allow Share',
      'allow_screenshot': 'Allow Screenshot',
      'allow_face_scan': 'Allow Face Scan',
      'submit': 'Submit',
      'view_photos': 'View Photos',
      'access_code': 'Access Code',
      'qr_code': 'QR Code',
      'plan_expires': 'Plan Expires',
      "event_name_required": "Please enter event name",
      "select_date": "Select date",
      "deal_amount_required": "Please enter deal amount",
      "amount_received_required": "Please enter received amount",
      "amount_hint": "0",
      "event_info_note": "A unique access code and QR code will be generated automatically after creating the event.",
      "uploading_photos": "Uploading photos...",
      "selected": "selected",
      'edit_profile': 'Edit Profile',
      'subscription': 'Subscription',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'privacy_policy': 'Privacy Policy',
      'logout': 'Logout',
      'version': 'Version',
      'profile_name': 'John Photographer',
    },
    'hi': {
      'app_name': 'पिकोरी',
      'tagline': 'कैप्चर. प्रबंधित करें. वितरित करें.',
      'login': 'लॉग इन करें',
      'register': 'रजिस्टर करें',
      'email': 'ईमेल',
      'full_name': 'पूरा नाम',
      'confirm_password': 'पासवर्ड पुष्टि करें',
      'enter_name': 'कृपया नाम दर्ज करें',
      'enter_email': 'कृपया ईमेल दर्ज करें',
      'enter_phone': 'कृपया फोन नंबर दर्ज करें',
      'enter_password': 'कृपया पासवर्ड दर्ज करें',
      'password_length': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
      'password_not_match': 'पासवर्ड मेल नहीं खा रहे',
      'phone': 'फ़ोन',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'home': 'होम',
      'events': 'इवेंट्स',
      'profile': 'प्रोफ़ाइल',
      'active_plan': 'सक्रिय योजना',
      'upgrade_plan': 'प्लान अपग्रेड करें',
      'create_event': 'इवेंट बनाएं',
      'event_name': 'इवेंट का नाम',
      'event_date': 'इवेंट की तारीख',
      'deal_amount': 'डील राशि',
      'amount_received': 'प्राप्त राशि',
      'total_photos': 'कुल फ़ोटो',
      'add_photos': 'फ़ोटो जोड़ें',
      'add_files': 'फ़ाइलें जोड़ें',
      'permissions': 'अनुमतियाँ',
      'allow_download': 'डाउनलोड की अनुमति दें',
      'allow_share': 'शेयर की अनुमति दें',
      'allow_screenshot': 'स्क्रीनशॉट की अनुमति दें',
      'allow_face_scan': 'फेस स्कैन की अनुमति दें',
      'submit': 'सबमिट करें',
      'view_photos': 'फ़ोटो देखें',
      'access_code': 'एक्सेस कोड',
      'qr_code': 'क्यूआर कोड',
      'plan_expires': 'प्लान समाप्त होगा',
      "event_name_required": "कृपया इवेंट का नाम दर्ज करें",
      "select_date": "तारीख चुनें",
      "deal_amount_required": "कृपया डील राशि दर्ज करें",
      "amount_received_required": "कृपया प्राप्त राशि दर्ज करें",
      "amount_hint": "0",
      "event_info_note": "इवेंट बनाने के बाद एक यूनिक एक्सेस कोड और QR कोड अपने आप जनरेट हो जाएगा।",
        "uploading_photos": "फोटो अपलोड हो रहे हैं...",
        "selected": "चुने गए",
      'edit_profile': 'प्रोफाइल संपादित करें',
      'subscription': 'सब्सक्रिप्शन',
      'notifications': 'सूचनाएं',
      'help_support': 'मदद और सहायता',
      'privacy_policy': 'गोपनीयता नीति',
      'logout': 'लॉगआउट',
      'version': 'संस्करण',
      'profile_name': 'जॉन फोटोग्राफर',
    },
  };
}
